In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv
/kaggle/input/datasets/binib1997/superstore/Superstore.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [4]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [5]:
# Create a series from a list

my_list = [10, 20, 30, 40, 50]

series = pd.Series(my_list)

series

0    10
1    20
2    30
3    40
4    50
dtype: int64

# 2. Create series from a dictionary

In [6]:
# Create a series from a dictionary

student_marks = {
    "Math": 85,
    "Physics": 90,
    "Chemistry": 88,
    "English": 92
}

marks_series = pd.Series(student_marks)

marks_series

Math         85
Physics      90
Chemistry    88
English      92
dtype: int64

# 3. Create a series from dataframe

In [7]:
# Create a series from dataframe column

iris_series = iris["sepal_length"]

iris_series

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

# 4. Apply below operations on a series to understand about a series

In [8]:
# head - first 5 values
print("Head:")
print(series.head())

# tail - last 5 values
print("\nTail:")
print(series.tail())

# sample - random values
print("\nSample:")
print(series.sample(3))

# size - number of elements
print("\nSize:")
print(series.size)

# dtype - data type
print("\nDtype:")
print(series.dtype)

# astype - change data type
print("\nAstype:")
print(series.astype(float))

# index - show index
print("\nIndex:")
print(series.index)

# values - show values
print("\nValues:")
print(series.values)

Head:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Tail:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Sample:
4    50
0    10
1    20
dtype: int64

Size:
5

Dtype:
int64

Astype:
0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64

Index:
RangeIndex(start=0, stop=5, step=1)

Values:
[10 20 30 40 50]

# 5. Change data-type of a series

In [9]:
# Create integer series

numbers = pd.Series([1, 2, 3, 4, 5])

print("Original datatype:")
print(numbers.dtype)

# Change integer to float

float_numbers = numbers.astype(float)

print("\nAfter changing datatype:")
print(float_numbers.dtype)

float_numbers

Original datatype:
int64

After changing datatype:
float64

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

# 6. Apply below mathematical operations on a series

In [10]:
# Create a series

series = pd.Series([10, 20, 30, 40, 50, 20, 30])

# count
print("Count:")
print(series.count())

# sum
print("\nSum:")
print(series.sum())

# product
print("\nProduct:")
print(series.product())

# min
print("\nMinimum:")
print(series.min())

# max
print("\nMaximum:")
print(series.max())

# mean
print("\nMean:")
print(series.mean())

# median
print("\nMedian:")
print(series.median())

# mode
print("\nMode:")
print(series.mode())

# describe
print("\nDescribe:")
print(series.describe())

# standard deviation
print("\nStandard Deviation:")
print(series.std())

# variance
print("\nVariance:")
print(series.var())

Count:
7

Sum:
200

Product:
7200000000

Minimum:
10

Maximum:
50

Mean:
28.571428571428573

Median:
30.0

Mode:
0    20
1    30
dtype: int64

Describe:
count     7.000000
mean     28.571429
std      13.451854
min      10.000000
25%      20.000000
50%      30.000000
75%      35.000000
max      50.000000
dtype: float64

Standard Deviation:
13.451854182690985

Variance:
180.95238095238096

# 7. Do 3 slicing operations on a series

In [11]:
# Create a series

series = pd.Series([10, 20, 30, 40, 50, 60, 70])

# 1. Slice first three elements
print("First three elements:")
print(series[0:3])


# 2. Slice middle elements
print("\nMiddle elements:")
print(series[2:6])


# 3. Slice last three elements
print("\nLast three elements:")
print(series[-3:])

First three elements:
0    10
1    20
2    30
dtype: int64

Middle elements:
2    30
3    40
4    50
5    60
dtype: int64

Last three elements:
4    50
5    60
6    70
dtype: int64

# Dataframe

# 1. Create a dataframe from a list

In [12]:
# Create dataframe from a list

data = [
    ["Rahim", 25, "Dhaka"],
    ["Karim", 30, "Chittagong"],
    ["Sadia", 22, "Sylhet"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])

df

    Name  Age        City
0  Rahim   25       Dhaka
1  Karim   30  Chittagong
2  Sadia   22      Sylhet

# 2. Apply below dataframe understanding operations

In [13]:
# head - first 5 rows
print("Head:")
print(df.head())


# tail - last 5 rows
print("\nTail:")
print(df.tail())


# sample - random rows
print("\nSample:")
print(df.sample(2))


# info - dataframe information
print("\nInfo:")
df.info()


# isnull - check missing values
print("\nMissing values:")
print(df.isnull())


# duplicated - check duplicate rows
print("\nDuplicate rows:")
print(df.duplicated())

Head:
    Name  Age        City
0  Rahim   25       Dhaka
1  Karim   30  Chittagong
2  Sadia   22      Sylhet

Tail:
    Name  Age        City
0  Rahim   25       Dhaka
1  Karim   30  Chittagong
2  Sadia   22      Sylhet

Sample:
    Name  Age        City
2  Sadia   22      Sylhet
1  Karim   30  Chittagong

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

Missing values:
    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False

Duplicate rows:
0    False
1    False
2    False
dtype: bool

# 2. Apply below dataframe attribute operations

In [14]:
# shape
print("Shape:")
print(df.shape)

# dtypes
print("\nData Types:")
print(df.dtypes)

# columns
print("\nColumns:")
print(df.columns)

# values
print("\nValues:")
print(df.values)

Shape:
(3, 3)

Data Types:
Name    object
Age      int64
City    object
dtype: object

Columns:
Index(['Name', 'Age', 'City'], dtype='object')

Values:
[['Rahim' 25 'Dhaka']
 ['Karim' 30 'Chittagong']
 ['Sadia' 22 'Sylhet']]

# 3. Apply below mathematical operations on a feature taken from dataframe

In [15]:
# Select Age feature
age = df["Age"]

# count
print("Count:")
print(age.count())

# sum
print("\nSum:")
print(age.sum())

# product
print("\nProduct:")
print(age.product())

# min
print("\nMinimum:")
print(age.min())

# max
print("\nMaximum:")
print(age.max())

# mean
print("\nMean:")
print(age.mean())

# median
print("\nMedian:")
print(age.median())

# mode
print("\nMode:")
print(age.mode())

# describe
print("\nDescribe:")
print(age.describe())

# standard deviation
print("\nStandard Deviation:")
print(age.std())

# variance
print("\nVariance:")
print(age.var())

Count:
3

Sum:
77

Product:
16500

Minimum:
22

Maximum:
30

Mean:
25.666666666666668

Median:
25.0

Mode:
0    22
1    25
2    30
Name: Age, dtype: int64

Describe:
count     3.000000
mean     25.666667
std       4.041452
min      22.000000
25%      23.500000
50%      25.000000
75%      27.500000
max      30.000000
Name: Age, dtype: float64

Standard Deviation:
4.041451884327381

Variance:
16.333333333333336

# Selection and filtering

In [ ]:
# loc
# iloc
# isin()
# logical operation (&, |, ~)

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [16]:
# Select 11th-20th rows and total_bill, tip columns

tips.loc[10:19, ["total_bill", "tip"]]

    total_bill   tip
10       10.27  1.71
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92
16       10.33  1.67
17       16.29  3.71
18       16.97  3.50
19       20.65  3.35

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [17]:
# Select 0th-20th rows and total_bill, tip, day columns

tips.loc[0:20, ["total_bill", "tip", "day"]]

    total_bill   tip  day
0        16.99  1.01  Sun
1        10.34  1.66  Sun
2        21.01  3.50  Sun
3        23.68  3.31  Sun
4        24.59  3.61  Sun
5        25.29  4.71  Sun
6         8.77  2.00  Sun
7        26.88  3.12  Sun
8        15.04  1.96  Sun
9        14.78  3.23  Sun
10       10.27  1.71  Sun
11       35.26  5.00  Sun
12       15.42  1.57  Sun
13       18.43  3.00  Sun
14       14.83  3.02  Sun
15       21.58  3.92  Sun
16       10.33  1.67  Sun
17       16.29  3.71  Sun
18       16.97  3.50  Sun
19       20.65  3.35  Sat
20       17.92  4.08  Sat

# 3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [18]:
tips[(tips["day"] == "Sun") & (tips["total_bill"] > 20)]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
11        35.26  5.00  Female     No  Sun  Dinner     4
15        21.58  3.92    Male     No  Sun  Dinner     2
44        30.40  5.60    Male     No  Sun  Dinner     4
46        22.23  5.00    Male     No  Sun  Dinner     2
47        32.40  6.00    Male     No  Sun  Dinner     4
48        28.55  2.05    Male     No  Sun  Dinner     3
52        34.81  5.20  Female     No  Sun  Dinner     4
54        25.56  4.34    Male     No  Sun  Dinner     4
112       38.07  4.00    Male     No  Sun  Dinner     3
113       23.95  2.55    Male     No  Sun  Dinner     2
114       25.71  4.00  Female     No  Sun  Dinner     3
116       29.93  5.07    Male     No  Sun  Dinner     4
153       24.55  2.00    Male     No  Sun  Dinner     4
155       29.85  5.14  Female     No  Sun  Dinner     5
156       48.17  5.00    Male     No  Sun  Dinner     6
157       25.00  3.75  Female     No  Sun  Dinner     4
160       21.50  3.50    Male     No  Sun  Dinner     4
165       24.52  3.48    Male     No  Sun  Dinner     3
166       20.76  2.24    Male     No  Sun  Dinner     2
167       31.71  4.50    Male     No  Sun  Dinner     4
173       31.85  3.18    Male    Yes  Sun  Dinner     2
175       32.90  3.11    Male    Yes  Sun  Dinner     2
179       34.63  3.55    Male    Yes  Sun  Dinner     2
180       34.65  3.68    Male    Yes  Sun  Dinner     4
181       23.33  5.65    Male    Yes  Sun  Dinner     2
182       45.35  3.50    Male    Yes  Sun  Dinner     3
183       23.17  6.50    Male    Yes  Sun  Dinner     4
184       40.55  3.00    Male    Yes  Sun  Dinner     2
185       20.69  5.00    Male     No  Sun  Dinner     5
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
189       23.10  4.00    Male    Yes  Sun  Dinner     3

# 4. Select passengers who are male and age greater than 50 from titanic

In [19]:
titanic[(titanic["Sex"] == "male") & (titanic["Age"] > 50)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.6500,E67,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.0000,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
406,407,0,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C
492,493,0,1,"Molson, Mr. Harry Markland",male,55.0,0,0,113787,30.5000,C30,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
582,583,0,2,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
631,632,0,3,"Lundahl, Mr. Johan Svensson",male,51.0,0,0,347743,7.0542,NaN,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
714,715,0,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [20]:
tips.query("sex == 'Female' and tip > 5")

     total_bill   tip     sex smoker   day    time  size
52        34.81  5.20  Female     No   Sun  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
155       29.85  5.14  Female     No   Sun  Dinner     5
214       28.17  6.50  Female    Yes   Sat  Dinner     3

# groupby

# 1. group on region based in store dataframe

In [22]:
# Group data based on Region

store.groupby("Region")
store.groupby("Region").size()

Region
Central    2323
East       2848
South      1620
West       3203
dtype: int64

# 2. Find region-wise average sales

In [23]:
# Average sales by region

store.groupby("Region")["Sales"].mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

# 3. Find region-wise average profit

In [24]:
store.groupby("Region")[["Sales","Profit"]].mean()

              Sales     Profit
Region
Central  215.772661  17.092709
East     238.336110  32.135808
South    241.803645  28.857673
West     226.493233  33.849032

# 4. Find region-wise maximum profit

In [25]:
# Find region-wise maximum profit

store.groupby("Region")["Profit"].max()

Region
Central    8399.9760
East       5039.9856
South      3177.4750
West       6719.9808
Name: Profit, dtype: float64

# 5. Apply multiple aggregate functions on region-wise sales

In [26]:
# Multiple aggregate functions on Sales by Region

store.groupby("Region")["Sales"].agg(["sum", "mean", "max", "min", "count"])

                 sum        mean        max    min  count
Region
Central  501239.8908  215.772661  17499.950  0.444   2323
East     678781.2400  238.336110  11199.968  0.852   2848
South    391721.9050  241.803645  22638.480  1.167   1620
West     725457.8245  226.493233  13999.960  0.990   3203

# 6. group on region and category wise

In [27]:
# Group by Region and Category

store.groupby(["Region", "Category"]).size()

Region   Category
Central  Furniture           481
         Office Supplies    1422
         Technology          420
East     Furniture           601
         Office Supplies    1712
         Technology          535
South    Furniture           332
         Office Supplies     995
         Technology          293
West     Furniture           707
         Office Supplies    1897
         Technology          599
dtype: int64

# 7. Find region and category wise average sales

In [28]:
# Region and Category wise average sales

store.groupby(["Region", "Category"])["Sales"].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [29]:
# Multiple aggregate functions on Region and Category wise Sales

store.groupby(["Region", "Category"])["Sales"].agg(
    ["mean", "min", "max", "sum"]
)

                               mean    min        max          sum
Region  Category
Central Furniture        340.534644  1.892   3504.900  163797.1638
        Office Supplies  117.458801  0.444   9892.740  167026.4150
        Technology       405.753124  1.980  17499.950  170416.3120
East    Furniture        346.574383  2.960   4416.174  208291.2040
        Office Supplies  120.044425  0.852   4663.736  205516.0550
        Technology       495.278469  2.970  11199.968  264973.9810
South   Furniture        353.309289  2.784   4297.644  117298.6840
        Office Supplies  126.282727  1.167   6354.950  125651.3130
        Technology       507.753952  1.584  22638.480  148771.9080
West    Furniture        357.302325  3.480   3610.848  252612.7435
        Office Supplies  116.422377  1.080   8187.650  220853.2490
        Technology       420.687533  0.990  13999.960  251991.8320

# Merging and joining

In [30]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [31]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [32]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [33]:
# Merge students and results using student_id

student_result = pd.merge(students, results, on="student_id")

# Merge with departments using department column

final_df = pd.merge(student_result, departments, on="department")

# Select required columns

final_df[["name", "faculty", "math", "python"]]

     name      faculty  math  python
0   Rahim  Engineering    85      90
1   Karim  Engineering    72      75
2   Hasan  Engineering    91      88
3   Nabil  Engineering    68      72
4  Tanvir  Engineering    77      80
5    Rafi     Business    88      92
6   Imran  Engineering    74      79
7    Arif  Engineering    95      96
8   Jahid     Business    81      85
9    Siam  Engineering    69      71

# 2. Department wise students count

In [34]:
# Count students department wise

students.groupby("department")["student_id"].count()

department
BBA    5
CSE    9
EEE    6
Name: student_id, dtype: int64

# 3. Faculty wise department count

In [35]:
# Merge students and departments

student_department = pd.merge(students, departments, on="department")

# Count departments by faculty

student_department.groupby("faculty")["department"].nunique()

faculty
Business       1
Engineering    2
Name: department, dtype: int64

# 4. Find department wise highest number on each subject

In [36]:
# Count students department wise

students.groupby("department")["student_id"].count()

department
BBA    5
CSE    9
EEE    6
Name: student_id, dtype: int64

# 5. Find faculty wise highest number on each subject

In [37]:
# Merge students and departments

student_department = pd.merge(students, departments, on="department")

# Count departments by faculty

student_department.groupby("faculty")["department"].nunique()

faculty
Business       1
Engineering    2
Name: department, dtype: int64

# Time-series

In [ ]:
# use climate dataset
climate

# 1. convert time into datetime

In [38]:
# Convert date column into datetime format

climate["date"] = pd.to_datetime(climate["date"])

climate.head()

        date   meantemp   humidity  wind_speed  meanpressure
0 2013-01-01  10.000000  84.500000    0.000000   1015.666667
1 2013-01-02   7.400000  92.000000    2.980000   1017.800000
2 2013-01-03   7.166667  87.000000    4.633333   1018.666667
3 2013-01-04   8.666667  71.333333    1.233333   1017.166667
4 2013-01-05   6.000000  86.833333    3.700000   1016.500000

# 2. set date as index

In [39]:
# Set date column as index

climate = climate.set_index("date")

climate.head()

             meantemp   humidity  wind_speed  meanpressure
date
2013-01-01  10.000000  84.500000    0.000000   1015.666667
2013-01-02   7.400000  92.000000    2.980000   1017.800000
2013-01-03   7.166667  87.000000    4.633333   1018.666667
2013-01-04   8.666667  71.333333    1.233333   1017.166667
2013-01-05   6.000000  86.833333    3.700000   1016.500000

# 3. Select row of 13 january, 2015

In [40]:
# Select 13 January 2015

climate.loc["2015-01-13"]

meantemp          12.250
humidity          77.875
wind_speed         4.875
meanpressure    1017.125
Name: 2015-01-13 00:00:00, dtype: float64

# 4. Select rows contains in april 2017

In [43]:
# Check rows in April 2017

climate.loc["2017-04"]

KeyError: '2017-04'

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [44]:
# Select rows between two dates

climate.loc["2014-09-11":"2014-09-25"]

             meantemp   humidity  wind_speed  meanpressure
date
2014-09-11  26.571429  85.714286   17.825000   1005.571429
2014-09-12  28.500000  73.000000    1.625000   1005.125000
2014-09-13  29.375000  68.250000    4.162500   1004.000000
2014-09-14  29.125000  65.500000    6.712500   1004.250000
2014-09-15  29.625000  63.125000    6.712500   1004.250000
2014-09-16  30.625000  65.125000    6.250000   1002.250000
2014-09-17  30.625000  61.875000    7.400000   1002.125000
2014-09-18  30.500000  62.375000    6.712500   1003.875000
2014-09-19  31.000000  56.625000    4.175000   1003.500000
2014-09-20  31.125000  55.750000    4.400000   1002.875000
2014-09-21  30.500000  54.875000    5.562500   1003.625000
2014-09-22  30.625000  50.000000   13.437500   1004.500000
2014-09-23  31.000000  47.000000   30.685714   1004.285714
2014-09-24  29.625000  53.000000    8.100000   1006.250000
2014-09-25  30.000000  52.500000    9.725000   1007.750000

# 6. Calculate month-wise average windspeed

In [45]:
# Month-wise average wind speed

climate["month"] = climate.index.month

climate.groupby("month")["wind_speed"].mean()

month
1     4.945358
2     6.531042
3     7.696836
4     8.783093
5     9.022982
6     9.381606
7     7.418752
8     6.923782
9     7.596360
10    4.761333
11    3.872533
12    4.761964
Name: wind_speed, dtype: float64

# 7. Calculate month-wise highest meantemp

In [46]:
# Month-wise highest mean temperature

climate["month"] = climate.index.month

climate.groupby("month")["meantemp"].max()

month
1     20.142857
2     23.875000
3     30.000000
4     35.687500
5     38.714286
6     38.500000
7     36.625000
8     34.125000
9     33.444444
10    33.269231
11    25.640000
12    25.000000
Name: meantemp, dtype: float64

# 8. Year-wise maximum, minimum and average humidity

In [47]:
# Extract year from date index

climate["year"] = climate.index.year

# Year-wise humidity statistics

climate.groupby("year")["humidity"].agg(
    ["max", "min", "mean"]
)

             max         min        mean
year
2013   94.000000   15.857143   63.046292
2014   96.857143   20.875000   59.767942
2015   98.000000   13.428571   61.430490
2016   94.300000   18.466667   58.740174
2017  100.000000  100.000000  100.000000

# 9. A new column contains previous 10 days average meantemp

In [48]:
# Create new column with previous 10 days average temperature

climate["previous_10_days_avg_meantemp"] = (
    climate["meantemp"].rolling(window=10).mean()
)

climate.head(15)

,meantemp,humidity,wind_speed,meanpressure,month,year,previous_10_days_avg_meantemp
date,,,,,,,
2013-01-01,10.000000,84.500000,0.000000,1015.666667,1,2013,NaN
2013-01-02,7.400000,92.000000,2.980000,1017.800000,1,2013,NaN
2013-01-03,7.166667,87.000000,4.633333,1018.666667,1,2013,NaN
2013-01-04,8.666667,71.333333,1.233333,1017.166667,1,2013,NaN
2013-01-05,6.000000,86.833333,3.700000,1016.500000,1,2013,NaN
2013-01-06,7.000000,82.800000,1.480000,1018.000000,1,2013,NaN
2013-01-07,7.000000,78.600000,6.300000,1020.000000,1,2013,NaN
2013-01-08,8.857143,63.714286,7.142857,1018.714286,1,2013,NaN
2013-01-09,14.000000,51.250000,12.500000,1017.000000,1,2013,NaN
2013-01-10,11.000000,62.000000,7.400000,1015.666667,1,2013,8.709048
2013-01-11,15.714286,51.285714,10.571429,1016.142857,1,2013,9.280476
2013-01-12,14.000000,74.000000,13.228571,1015.571429,1,2013,9.940476
2013-01-13,15.833333,75.166667,4.633333,1013.333333,1,2013,10.807143
2013-01-14,12.833333,88.166667,0.616667,1015.166667,1,2013,11.223810
2013-01-15,14.714286,71.857143,0.528571,1015.857143,1,2013,12.095238